[DEFAULT]
debug=true
use_stderr=true
logging_default_format_string= %(asctime)s.%(msecs)03d %(process)d %(levelname)s %(name)s %(lineno)s [- - - - - - -] %(instance)s%(message)s
log_dir=/var/log
log_rotation_type=size
max_logfile_count=2
max_logfile_size_mb=10


[database]
connection=mysql+pymysql://root:PASSWD123456@82.156.225.136:3306/MALL?charset=utf8